apiVersion: v1
kind: Pod

metadata:
  name: fortune-cephrbd-pvc

spec:
  containers:
  - image: dockerhub.vagrant.info/luksa/fortune
    name: html-generator-cephfs
    volumeMounts:
    - name: vol
      mountPath: /var/htdocs
    imagePullPolicy: IfNotPresent
  - image: dockerhub.vagrant.info/library/nginx:alpine
    name: web-server-cephfs
    volumeMounts:
    - name: vol
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
    imagePullPolicy: IfNotPresent
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: pvc-fast-1g
      readOnly: false
