apiVersion: apps/v1
kind: ReplicaSet

metadata: 
  name: rs-kubia
spec:
  replicas: 3
  selector:
    matchExpressions:
      - {key: env, operator: In, values: [prod, canary]}
      - {key: build, operator: NotIn, values: [debug]}
  template: 
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - image: "dockerhub.vagrant.info/library/kubia:v3.0.0"
        name: kubia1
      - image: "dockerhub.vagrant.info/library/kubia:v3.0.0"
        name: kubia2
      terminationGracePeriodSeconds: 2
